### ISSUE TITLE
KeyError : MAPBOX_KEY 

### ISSUE THREAD

**Issue by winash12** [guidocioni/icon_globe#2]
All the plotting files throw up the same error 

`Traceback (most recent call last):
  File "plot_meteogram.py", line 10, in <module>
    from utils import *
  File "/home/winash12/ICON/plot/ICON_forecast/plotting/utils.py", line 27, in <module>
    apiKey = os.environ['MAPBOX_KEY']
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'MAPBOX_KEY'`

There is some hard coding going on here - 

`if 'MODEL_DATA_FOLDER' in os.environ:
    folder = os.environ['MODEL_DATA_FOLDER']
else:
    folder = '/home/ekman/ssd/guido/icon-globe/'`

I will change that of course but apart from that is there anything else ?

**Comment by guidocioni** [comment]
Have a look at this issue https://github.com/guidocioni/icon_d2/issues/1.

The code was never meant to be portable so there are many hardcoded parts and unfortunately you'll have to discover them yourself
